//
// Created by brent on 5/10/22.
//

#ifndef MAO_AI_CORRECTIONSTATUS_H
#define MAO_AI_CORRECTIONSTATUS_H

enum CorrectionStatus{
    PLAYED_OUT_OF_TURN,
    NOT_PLAYED_AT_TURN,
    INVALID_CARD,
    INVALID_ACT,
    DREW_CARD_OUT_OF_TURN
};

#endif //MAO_AI_CORRECTIONSTATUS_H
